:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

During this module you will configure both nodes to host secure container registries.
The registry software runs in a container and listens on port 5000. Configuring the 
registry consists of generating a self-signed SSL certificate and running the 
container. Two simple bash scripts are provided to do this. Once the registries are
configured and running, the `curl` command can be used to test basic connectivity.

[[anchor-1]]
=== Configure and Start Registries

.Login to *both* `node1.{GUID}.internal` and `node2.{GUID}.internal` to configure the registries.
--
[source,subs="{markup-in-source}"]
----
$ *ssh node1*
$ *cd registry-files/gen-certs*
----
--

.Run the `gen-cert.sh` script to generate an SSL certificate
--
[source,subs="{markup-in-source}"]
----
$ *sh ./gen-cert.sh*
----
[subs="{markup-in-source}"]
----
+ touch myserver.key
+ chmod 600 myserver.key
+ openssl req -new -newkey rsa:4096 -nodes -sha256 -config myserver.cnf -keyout myserver.key -out myserver.csr
+..........+...+........+..........+.....+.........+...+.+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
+ openssl x509 -signkey myserver.key -in myserver.csr -req -days 2000 -out myserver.cert -extensions req_ext -extfile myserver.cnf
+ openssl x509 -noout -in myserver.cert -serial -issuer -dates -subject -ext subjectAltName
serial=26D386D4CF34E06B73240B4DD247D5D4C34477FC
issuer=O = Red Hat Lab, CN = node1.{GUID}.internal
notBefore=Apr  5 17:36:21 2023 GMT
notAfter=Sep 25 17:36:21 2028 GMT
subject=O = Red Hat Lab, CN = node1.{GUID}.internal
X509v3 Subject Alternative Name:
    DNS:node1.{GUID}.internal
----
--

.Now move up one directory and run the `run-registry.sh` script to start the registry container
--
[source,subs="{markup-in-source}"]
----
$ *cd ..*
$ *loginctl enable-linger*
$ *sh ./run-registry.sh*
----
----
Adding password for user redhat
750ef695e4b66b00919e725bc2559db6ec2f9407e1f31358686b4339017c2ed5
----
--

=== Testing the registries

.Use `curl` to test that the registry service is running
--
[source,subs="{markup-in-source}"]
----
$ *curl  --user redhat:redhat https://node1.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
--

<<anchor-1,Repeat>> the same for node2

=== Configure the bastion

Perform the following on the bastion.

.Copy the SSL certificates from the registry servers and update the trust store
--
[source,subs="{markup-in-source}"]
----
$ *sudo scp node1.{GUID}.internal:/etc/pki/ca-trust/source/anchors/myserver.cert /etc/pki/ca-trust/source/anchors/node1.cert*

$ *sudo scp node2.{GUID}.internal:/etc/pki/ca-trust/source/anchors/myserver.cert /etc/pki/ca-trust/source/anchors/node2.cert*

$ *sudo update-ca-trust*
----
--

.Test the registries from the bastion
--
[source,subs="{markup-in-source}"]
----
$ *curl  --user redhat:redhat https://node1.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
[source,subs="{markup-in-source}"]
----
$ *curl  --user redhat:redhat https://node2.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
--

Now that the registries have been configured, the remainder of the commands will be run on the bastion.
