:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

During this module you will configure a node to host a secure container registry.
The registry software runs in a container and listens on port 5000. Configuring the 
registry consists of generating a SSL certificate and running the container. We have
some bash helper scripts to make it easier. Once the registry is configured and
running, the `curl` command can be used to test basic connectivity.

=== Configure and Start the Registry Container

.Login to `node1.{GUID}.internal` to configure the registry.
--
[source,subs="{markup-in-source}"]
----
$ *ssh node1*
$ *cd /home/lab-user/gen-certs*
----
--

.Run the `gen-cert.sh` script to generate an SSL certificate
--
[source,subs="{markup-in-source}"]
----
$ *./gen-cert.sh*
----
[subs="{markup-in-source}"]
----
+ openssl genrsa -out myserver.key 2048
+ openssl req -new -key myserver.key -out myserver.csr -config certificate.cnf
+ openssl x509 -req -in myserver.csr -out myserver.pem -CA CA/CA_cert.pem -CAkey CA/CA_key.pem -CAcreateserial -days 365 -sha256 -extfile certificate.cnf
----
--

.Now move up and into registry-files/ directory and run the script to create the registry container
--
[source,subs="{markup-in-source}"]
----
$ *cd /home/lab-user/registry-files*
$ *./create-registry.sh*
----
--

This will create the registry container but not start it, now we will create a
systemd user service that runs as the lab-user on boot

=== Create a Systemd Service

.Create the systemd user service directories
--
[source,subs="{markup-in-source}"]
----
$ *cd ~*
$ *mkdir -pv /home/lab-user/.config/systemd/user*
----
----
mkdir: created directory '/home/lab-user/.config/systemd'
mkdir: created directory '/home/lab-user/.config/systemd/user'
----
--

We can use podman to generate a systemd service file. In this case we are specifying the name of the
service to be *registry* as well as adding logic with `--new` to create a new container when the
service is started and stop and remove the container when the service is stopped.

.Generate a systemd unit file for the registry service
--
[source,subs="{markup-in-source}"]
----
$ *podman generate systemd --new --name registry > /home/lab-user/.config/systemd/user/container-registry.service*
----
--

.Start the registry as a systemd user service
--
[source,subs="{markup-in-source}"]
----
$ *systemctl --user daemon-reload*
$ *systemctl --user start container-registry*
----
--

.Check that the unit started correctly and is running the registry container
--
[source,subs="{markup-in-source}"]
----
$ *systemctl --no-pager --user status container-registry*
----
----
● container-registry.service - Podman container-registry.service
     Loaded: loaded (/home/lab-user/.config/systemd/user/container-registry.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2023-05-02 16:01:14 UTC; 6min ago
       Docs: man:podman-generate-systemd(1)
   Main PID: 1722 (conmon)
      Tasks: 14 (limit: 48156)
     Memory: 26.0M
        CPU: 254ms
     CGroup: /user.slice/user-1001.slice/user@1001.service/app.slice/container-registry.service
...
----
--

[IMPORTANT]
--
Red lines in the log output shows that the line was printed to stderr instead of stdout and can be safely
ignored in this context
--

Now that we have the registry service running we can set it to start on system boot. By default in RHEL 9
systemd stops all processes associated with a ssh connection so we use `loginctl` to enable processes to
"linger" after the ssh connection is terminated.

.Enable the registry service to run on boot
--
[source,subs="{markup-in-source}"]
----
$ *loginctl enable-linger*
$ *systemctl --user enable container-registry*
----
----
----
--

.Use `curl` to test that the registry service is running
--
[source,subs="{markup-in-source}"]
----
$ *curl --user redhat:redhat https://node1.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
--

The registry service should already be running on node2 so we can return to the bastion and test.

=== Test the Registries

.Test the registries from the bastion
--
[source,subs="{markup-in-source}"]
----
$ *curl --user redhat:redhat https://node1.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
[source,subs="{markup-in-source}"]
----
$ *curl --user redhat:redhat https://node2.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
--

You have successfully deployed a registry running in rootless containers with systemd integration. We
will be running the rest of the lab from the bastion.
