:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

During this module you will configure both nodes to host secure container registries.
The registry software runs in a container and listens on port 5000. Configuring the 
registry consists of generating a SSL certificate and running the container. We have
some bash helper scripts to make it easier. Once the registries are configured and
running, the `curl` command can be used to test basic connectivity.

[[anchor-1]]
=== Configure and Start Registries

.Login to *both* `node1.{GUID}.internal` and `node2.{GUID}.internal` to configure the registries.
--
[source,subs="{markup-in-source}"]
----
$ *ssh node1*
$ *cd gen-certs*
----
--

.Run the `gen-cert.sh` script to generate an SSL certificate
--
[source,subs="{markup-in-source}"]
----
$ *./gen-cert.sh*
----
[subs="{markup-in-source}"]
----
+ openssl genrsa -out myserver.key 2048
+ openssl req -new -key myserver.key -out myserver.csr -config certificate.cnf
+ openssl x509 -req -in myserver.csr -out myserver.pem -CA CA/CA_cert.pem -CAkey CA/CA_key.pem -CAcreateserial -days 365 -sha256 -extfile certificate.cnf
----
--

.Now move up and into registry-files/ directory and run the script to create the registry container
--
[source,subs="{markup-in-source}"]
----
$ *cd ../registry-files*
$ *./create-registry.sh*
----
--

This will create the registry container but not start it, now we will create a
systemd user service that runs as the lab-user on boot

.Create a systemd unit file for the registry user service and start it
--
[source,subs="{markup-in-source}"]
----
$ *mkdir -pv $HOME/.config/systemd/user*
$ *podman generate systemd --new --name registry > $HOME/.config/systemd/user/container-registry.service*
$ *systemctl --user daemon-reload*
$ *systemctl --user start container-registry*
----
----
----
--

.Check that the unit started correctly and is running the registry container
--
[source,subs="{markup-in-source}"]
----
$ *systemctl --no-pager --user status container-registry*
----
----
● container-registry.service - Podman container-registry.service
     Loaded: loaded (/home/lab-user/.config/systemd/user/container-registry.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2023-05-02 16:01:14 UTC; 6min ago
       Docs: man:podman-generate-systemd(1)
   Main PID: 1722 (conmon)
      Tasks: 14 (limit: 48156)
     Memory: 26.0M
        CPU: 254ms
     CGroup: /user.slice/user-1001.slice/user@1001.service/app.slice/container-registry.service
...
----
--

.Enable the registry service to run on boot
--
[source,subs="{markup-in-source}"]
----
$ *loginctl enable-linger*
$ *systemctl --user enable container-registry*
----
----
----
--

.Use `curl` to test that the registry service is running
--
[source,subs="{markup-in-source}"]
----
$ *curl --user redhat:redhat https://node1.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
--

<<anchor-1,Repeat>> the same for node2

=== Testing the registries

.Test the registries from the bastion
--
[source,subs="{markup-in-source}"]
----
$ *curl  --user redhat:redhat https://node1.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
[source,subs="{markup-in-source}"]
----
$ *curl  --user redhat:redhat https://node2.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":[]}
----
--

You have successfully deployed two registries running in rootless containers with systemd integration. We will be running the rest of the lab from the bastion.
