:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

=== What is a pod?

A pod is a group of one or more containers with shared storage, network and a specification for how to run the containers. In this module you'll be working at the container level. Since you are here to learn more about
container security, we have a quick review of 
container basics then get right into the good stuff. 

Podman (Pod Manager) is a fully featured container engine that is a simple daemon-less tool. Podman provides a Docker-CLI comparable command line experience that eases the transition and allows the management of pods, containers and images. Simply put, `alias docker=podman`. 

Also, most `podman` commands can be run as a regular,
non-root user, without requiring additional privileges. This presents significant security and auditing advantages
over client-server based architectures.


==== References

* https://kubernetes.io/docs/concepts/workloads/pods/pod/[Pod concepts]
* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index[podman user guide]

=== The Universal Base Image

The container image that you will be using through out most of this lab is the RHEL 9 Universal Base Image https://access.redhat.com/containers/#/product/5c180b28bed8bd75a2c29a63[(UBI)]. The UBI is designed and engineered to be the base layer for containerized applications, middleware and utilities. This base image is freely distributable. However, Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. When you get a chance, read more about https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_containers/index#using_red_hat_universal_base_images_standard_minimal_and_runtimes[ using the UBI]. 

.Pull the RHEL 9 UBI image from RedHat's container registry. Do this on the bastion node.
--
[source,subs="{markup-in-source}"]
----
$ *podman pull %RHEL_CONTAINER%*
----
----
Trying to pull %RHEL_CONTAINER%...
Getting image source signatures
...
...
Storing signatures
0c46e5c7a82a97d21447ee6a1ef0d407317642c9361b562456395e087be08774
----
--

.Now do the same as the root user. 
--
[source,subs="{markup-in-source}"]
----
$ *sudo podman pull %RHEL_CONTAINER%*
----
--

The container images for these different users are stored in unique locations. Use the `podman` command to find out where they are stored in the file system.

.Hint
--
[source,subs="{markup-in-source}"]
----
$ *podman inspect %RHEL_CONTAINER% | grep UpperDir*
----
--

Notice that pulling the UBI does not require 
authentication from RedHat's registries.

Next, we'll work with the registries that were configured
in the previous modules.

=== Tagging and pushing images to a remote registry

Before an image can be pushed to a registry, it must be tagged 
appropriately.

.Pull an image from quay.io
--
[source,subs="{markup-in-source}"]
----
$ podman pull quay.io/bkozdemb/hello
----
--

.Confirm the pull worked
--
[source,subs="{markup-in-source}"]
----
$ *podman images*
----
----
REPOSITORY                            TAG      IMAGE ID       CREATED      SIZE
quay.io/bkozdemb/hello                latest  398a3b0bab81  7 months ago   250 MB
----
--

.Next tag the image for the remote registry hosted at node1.{GUID}.internal
--
[source,subs="{markup-in-source}"]
----
$ *podman tag quay.io/bkozdemb/hello node1.{GUID}.internal:5000/mynamespace/hello*
----
--

.Confirm the tag is correct
--
[source,subs="{markup-in-source}"]
----
$ *podman images*
----
[source,subs="{markup-in-source}"]
----
REPOSITORY                            TAG      IMAGE ID       CREATED      SIZE
quay.io/bkozdemb/hello                latest  398a3b0bab81  7 months ago   250 MB
node1.{GUID}.internal:5000/mynamespace/hello  latest  398a3b0bab81  7 months ago
   250 MB
----
--

.Login to the `node1.{GUID}.internal` registry. Do the same for `node2.{GUID}.internal`. 
[source,subs="{markup-in-source}"]
----
$ *podman login -u redhat -p redhat node1.{GUID}.internal:5000*
----
----
Login Succeeded!
----
[source,subs="{markup-in-source}"]
----
$ *podman login -u redhat -p redhat node2.{GUID}.internal:5000*
----
----
Login Succeeded!
----

[IMPORTANT]
.If the following error message is reported
====
[subs="{markup-in-source}"]
----
Error: error authenticating creds for "node1.{GUID}.internal:5000": error pinging docker registry node1.{GUID}.internal:5000: Get "https://node1.{GUID}.internal:5000/v2/": x509: certificate relies on legacy 
Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
----

The `GODEBUG` variable needs to be set.
[source,subs="{markup-in-source}"]
----
$ *export GODEBUG=x509ignoreCN=0*
----
====

.Finally, push the image
--
[source,subs="{markup-in-source}"]
----
$ *podman push node1.{GUID}.internal:5000/mynamespace/hello*
----
----
Getting image source signatures
Copying blob 8da573feae5f: 205.77 MiB / 205.77 MiB [========================] 5s
Copying blob 6ef321d2357f: 10.00 KiB / 10.00 KiB [==========================] 5s
Copying config cc7efd763847: 0 B / 4.36 KiB [-------------------------------] 0s
Writing manifest to image destination
Writing manifest to image destination
Storing signatures
----
--

.Confirm the push succeeded and the repository was created.
--
[source,subs="{markup-in-source}"]
----
$ *curl --user redhat:redhat https://node1.{GUID}.internal:5000/v2/_catalog*
----
----
{"repositories":["hello","mynamespace/hello"]}
----
--

=== Working with root and rootless containers.

Podman supports storing and running root and rootless containers. Effectively, each user manages it's own containers.

The UBI container images should be loaded into the podman's local image storage for both root and rootless (lab-user) usage. 

Confirm these images exist using `podman`. Note the `podman` command may be run as **root** (privileged) or as a **root-less** (non-privileged) user.

.Examine container image storage
--
[source,subs="{markup-in-source}"]
----
$ *sudo podman images*
$ *podman images*
----
----
REPOSITORY                            TAG      IMAGE ID       CREATED       SIZE
%RHEL_CONTAINER%   latest   8121a9f5303b   8 days ago   240 MB
----
--

.Where are the container images actually stored? 
--
It depends on the user. For a rootless user, they are stored in the home directory. 
There are separate directories for images (once they are pulled) and containers
(once they have run).
[source,subs="{markup-in-source}"]
----
$ *ls $HOME/.local/share/containers/storage*
----
----
cache/	libpod/  mounts/  overlay/  overlay-containers/  overlay-images/  overlay-layers/  storage.lock  tmp/  userns.lock
----
--

.Here is an example to locate the storage directory for an image
--
[source,subs="{markup-in-source}"]
----
$ *podman images*
----
----
REPOSITORY                           TAG     IMAGE ID      CREATED        SIZE
quay.io/bkozdemb/hello               latest  398a3b0bab81  7 months ago   250 MB
----
--

.Use the image ID to locate the actual layers
--
[source,subs="{markup-in-source}"]
----
$ *ls -R .local/share/containers | grep 398a3b0bab81*
----
----
398a3b0bab8109a059a2a1cb733553cab01d7350bf439063b3b39b02937c9064/
.local/share/containers/storage/overlay-images/398a3b0bab8109a059a2a1cb733553cab01d7350bf439063b3b39b02937c9064:
----
--

How would you do the same for a running container? You should be able to answer that soon.

.For the root user, image layers are stored in `/var/lib/containers`
--
[source,subs="{markup-in-source}"]
----
$ *sudo ls /var/lib/containers/storage*
----
----
overlay  overlay-containers  overlay-layers  overlay-locks
----
--

Let's start with a few more warmup exercises. Note that a random _container ID_ is returned when the container starts.

.Run a rootless container
[source,subs="{markup-in-source}"]
----
$ *podman run --name=rootless -d %RHEL_CONTAINER% sleep 999*
----
----
815dd74131decfed827b4087785e54b780eef12e44392ff1146c31179b29a855
----

.Examine the running containers
[source,subs="{markup-in-source}"]
----
$ *podman ps*
----
----
CONTAINER ID  IMAGE                                       COMMAND    CREATED         STATUS             PORTS  NAMES
e05c3fc400eb  %RHEL_CONTAINER%:latest  sleep 999  2 seconds ago   Up 2 seconds ago          rootless
----

.Now do the same for a root container
[source,subs="{markup-in-source}"]
----
$ *sudo podman run --name=root -d %RHEL_CONTAINER% sleep 999* 
----
----
815dd74131decfed827b4087785e54b780eef12e44392ff1146c31179b29a855
----
[source,subs="{markup-in-source}"]
----
$ *sudo podman ps*
----
----
CONTAINER ID  IMAGE                       COMMAND    CREATED         STATUS             PORTS  NAMES
493da8f543de  %RHEL_CONTAINER%  sleep 999  43 seconds ago  Up 42 seconds ago         root
----

=== Stopping and removing containers

.With grace
--
[source,subs="{markup-in-source}"]
----
$ *podman stop rootless*
$ *podman rm rootless*

$ *sudo podman stop root*
$ *sudo podman rm root*
----
--

.With brute
--
[source,subs="{markup-in-source}"]
----
$ *podman rm -f rootless*
$ *sudo podman rm -f root*
----
--

=== Container process information

Podman top can be used to display information about the running process of the container. Use it to answer the following.

.What command is run when the container is run?
--
[source,subs="{markup-in-source}"]
----
$ *podman run --name=rootless -d %RHEL_CONTAINER% sleep 999*
----
--

.How long has this container been running?
--
[source,subs="{markup-in-source}"]
----
$ *podman top -l args etime*
----
--

.Clean up
--
[source,subs="{markup-in-source}"]
----
$ *podman rm -f rootless*
----
--

In the next section we will build on this with how rootless containers use user namespacing to run.
