:imagesdir: images
:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

=== Using the podman API

In this lab, you will use `podman` in a client/server manner. 
The Podman v2.0 RESTful API consists of the Libpod API providing support for Podman, and a Docker-compatible API. 
With this new REST API, podman may be called from platforms such as cURL, Postman, Google’s Advanced REST 
client, and many others.


=== Client/Server Exercise

This exercise can be performed on the bastion as a **rootless** user. We will start by setting up a Python environment

.Create a python virtual environment
--
[source,subs="{markup-in-source}",role=execute]
----
python -m venv ~/venv
----
--

.Activate the virtual environment
--
[source,subs="{markup-in-source}",role=execute]
----
source ~/venv/bin/activate
----
--

The shell prompt should change.

----
(venv) [lab-user@bastion 0 ~]$
----

.Upgrade pip and install the requests package
--
[source,subs="{markup-in-source}",role=execute]
----
pip install pip requests -U
----
--

.Add the following Python client code into a file called `podman-client.py`. Click the arrow to create the file
--
[source,subs="{markup-in-source}",role=execute]
----
cat >> podman-client.py <<EOF
import json
import requests

#
# Set the url variable to reflect your podman api server.
#
url = "http://localhost:8080"

#
# Create and call the REST request then print the response.
#
req = f'{url}/v1.40.0/libpod/info'
response = requests.get(req)
print(response)

response.raise_for_status()

#
# Convert the json response to a python dict and print the security info.
#
info = json.loads(response.text)
print(info['host']['security'])
EOF
----
--

.In the upper terminal, launch the podman API service
--
[source,subs="{markup-in-source}",role=execute-1]
----
podman system service tcp:localhost:8080 --log-level=debug --time=0
----
--

.In the lower terminal, activate the python environment
--
[source,subs="{markup-in-source}",role=execute-2]
----
source ~/venv/bin/activate
----
--

.Now run the `podman-client.py` program that was just created
--
[source,subs="{markup-in-source}",role=execute-2]
----
python podman-client.py
----
----
<Response [200]>
<class 'dict'>
{'apparmorEnabled': False, 'capabilities': 'CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT', 'rootless': True, 'seccompEnabled': True, 'selinuxEnabled': True}
----
--

=== Bonus Exercise

Bastion Client and Remote Node Service

Login to either one of the nodes, and run the podman service. Then on the bastion, change the `url` variable in the `podman-client.py` file so API 
calls are made to the podman service running on the remote node instead of the bastion.

=== Docker Compose 

This exercise must be performed as a **rootful** user. In a future version of
RHEL, this restriction will be lifted.

.Become root
--
[source,subs="{markup-in-source}",role=execute]
----
sudo -i
----
--

.Install the `podman-docker` package
--
[source,subs="{markup-in-source}",role=execute]
----
sudo yum install podman-docker -y
----
--

Here is why that is necessary.

Docker compose looks for docker's socket, which is normally `/var/run/docker.sock`
We need to symlink podman's rootful socket there, something like `ln -s /run/podman/podman.sock /var/run/docker.sock`
The podman-docker package also makes a symlink between podman binary and docker. (i.e. `ln -s /usr/bin/podman /usr/bin/docker`)

.As root, start the podman service
--
[source,subs="{markup-in-source}",role=execute]
----
podman --log-level=debug system service -t0
----
--

.In the lower terminal window become a root user
--
[source,subs="{markup-in-source}",role=execute-2]
----
sudo -i
----
--

.Next, create a compose file called `docker-compose.yml`. This container is a simple python web server
--
[source,subs="{markup-in-source}",role=execute-2]
----
cat >> docker-compose.yml << EOF
version: "3.9"
services:
  hello:
    image: "quay.io/bkozdemb/hello"
    ports:
      - "8080:8080"
EOF
----
--

.Setup a Python environment
--
[source,subs="{markup-in-source}",role=execute-2]
----
python -m venv venv
----
--

.Activate the environment
--
[source,subs="{markup-in-source}",role=execute-2]
----
source venv/bin/activate
----
--

.Upgrade `pip` and install `docker-compose`
--
[source,subs="{markup-in-source}",role=execute-2]
----
pip install pip docker-compose -U
----
--

.Run the docker-compose application in the background
--
[source,subs="{markup-in-source}",role=execute-2]
----
docker-compose up -d
----
----
Creating network "lab-user_default" with the default driver
Creating lab-user_hello_1 ... done
----
--

.Confirm the application is running
--
[source,subs="{markup-in-source}",role=execute-2]
----
docker ps
----
----
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                          COMMAND               CREATED        STATUS            PORTS                   NAMES
ae404eeedcc7  quay.io/bkozdemb/hello:latest  /usr/bin/python3 ...  6 seconds ago  Up 6 seconds ago  0.0.0.0:8080->8080/tcp  lab-user_hello_1
----
--

.Visit the application on port 8080
--
[source,subs="{markup-in-source}",role=execute-2]
----
curl http://127.0.0.1:8080
----
----
The Python http server is listening on port 8080
----
--

.Shut down the application
--
[source,subs="{markup-in-source}",role=execute-2]
----
docker-compose down
----
--

=== References

https://www.redhat.com/sysadmin/podman-python-bash[Python example Blog post]

https://raw.githubusercontent.com/containers/Demos/main/restful_api/clean_storage.py[Clean storage code]

https://docs.docker.com/compose/gettingstarted/[Docker compose example]

https://pypi.org/project/docker-compose/[Docker-Compose python]

https://github.com/containers/podman/tree/main/test/compose[Podman compose tests]

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#assembly_using-the-container-tools-api_using-the-container-tools-cli[Red Hat container docs]

