:imagesdir: images
:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

In this lab, you will use `podman` in a client/server manner. 
The Podman v2.0 RESTful API consists of the Libpod API providing support for Podman, and a Docker-compatible API. 
With this new REST API, podman may be called from platforms such as cURL, Postman, Google’s Advanced REST 
client, and many others.


==== Podman API demo

This exercise can be performed on the bastion as a **rootless** user.

.To get started, set up a Python environment
[source,subs="{markup-in-source}",role=execute]
```
sudo yum install python38 -y
```
[source,subs="{markup-in-source}",role=execute]
```
sudo alternatives --set python /usr/bin/python3.8
```
[source,subs="{markup-in-source}",role=execute]
```
python --version
```
Output
```
Python 3.8.6
```

.Create a python virtual environment and activate it.
[source,subs="{markup-in-source}",role=execute]
```
python -m venv ~/venv
```
[source,subs="{markup-in-source}",role=execute]
```
source ~/venv/bin/activate
```

The shell prompt should change.
```
(venv) [lab-user@bastion 0 ~]$
```

.Install a few dependencies.
[source,subs="{markup-in-source}",role=execute]
```
pip install pip requests -U
```

.Add the following Python client code into a file called `podman-client.py`. Copy/paste should work here.

[source,subs="{markup-in-source}",role=execute]
```
cat >> podman-client.py <<EOF
import json
import requests

url = "http://localhost:8080"
req = f'{url}/v1.40.0/libpod/info'
response = requests.get(req)
print(response)

response.raise_for_status()

info = json.loads(response.text)
print(type(info))
print(info['host']['security'])
EOF
```

.In the upper terminal, launch the podman API service.
[source,subs="{markup-in-source}",role=execute]
```
podman system service tcp:localhost:8080 --log-level=debug --time=0
```

.In the lower termnal, activate the python environment then run the `podman-client.py`  that was just created.

[source,subs="{markup-in-source}",role=execute]
```
source ~/venv/bin/activate
```

[source,subs="{markup-in-source}",role=execute]
```
python podman-client.py
```

Expected output.
```
<Response [200]>
<class 'dict'>
{'apparmorEnabled': False, 'capabilities': 'CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT', 'rootless': True, 'seccompEnabled': True, 'selinuxEnabled': True}
```

==== Bonus exercise

Bastion Client and Node Service

.Login to one of the nodes, and run the podman service. Then on the bastion, change the `url`
variable in the `podman-client.py` so API calls are made to the podman service running
on the remote node.

==== Docker Compose 

This exercise must be performed as a **rootful** user. In a future version of
RHEL, this restriction will be lifted.

[source,subs="{markup-in-source}",role=execute]
```
sudo -i
```

.Install the `podman-docker` package. 

Here is why

Docker compose looks for docker's socket, which is normally `/var/run/docker.sock`
We need to symlink podman's rootful socket there, something like `ln -s /run/podman/podman.sock /var/run/docker.sock`
The podman-docker package also makes a symlink between podman binary and docker. (i.e. `ln -s /usr/bin/podman /usr/bin/docker`)

.To get started, set up a Python environment
[source,subs="{markup-in-source}",role=execute]
```
sudo yum install python38 -y
```

.As root, start the podman service.
[source,subs="{markup-in-source}",role=execute]
```
podman --log-level=debug system service -t0
```

.In a separate terminal window as root, create a compose file called `docker-compose.yml`

[source,subs="{markup-in-source}",role=execute]
```
sudo -i
```

[source,subs="{markup-in-source}",role=execute]
```
cat >> docker-compose.yml << EOF
version: "3.9"
services:
  hello:
    image: "quay.io/bkozdemb/hello"
    ports:
      - "8080:8080"
EOF
```

.Setup a Python environment.
[source,subs="{markup-in-source}",role=execute]
```
python -m venv venv
```
[source,subs="{markup-in-source}",role=execute]
```
source venv/bin/activate
```

.Upgrade `pip` and install `docker-compose`.
[source,subs="{markup-in-source}",role=execute]
```
pip install pip docker-compose -U
```

.Run the application in the background.
[source,subs="{markup-in-source}",role=execute]
```
docker-compose up -d
```
Expected output.
```
Creating network "lab-user_default" with the default driver
Creating lab-user_hello_1 ... done
```

.Confirm the application is running.
[source,subs="{markup-in-source}",role=execute]
```
docker ps
```
Sample output.
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                          COMMAND               CREATED        STATUS            PORTS                   NAMES
ae404eeedcc7  quay.io/bkozdemb/hello:latest  /usr/bin/python3 ...  6 seconds ago  Up 6 seconds ago  0.0.0.0:8080->8080/tcp  lab-user_hello_1
```

.Visit the application on port 8080.
[source,subs="{markup-in-source}",role=execute]
```
curl http://127.0.0.1:8080
```

Expected output.
```
The Python http server is listening on port 8080
```

.Shutdown the application.
[source,subs="{markup-in-source}",role=execute]
```
docker-compose down
```

References

https://www.redhat.com/sysadmin/podman-python-bash[Python example Blog post]
https://raw.githubusercontent.com/containers/Demos/main/restful_api/clean_storage.py[Clean storage code]
https://docs.docker.com/compose/gettingstarted/[Docker compose example]
https://pypi.org/project/docker-compose/[Docker-Compose python]
https://github.com/containers/podman/tree/main/test/compose[Podman compose tests]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#assembly_using-the-container-tools-api_using-the-container-tools-cli[Red Hat container docs]

