:imagesdir: images
:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

=== Using the podman API

In this lab, you will use `podman` in a client/server manner. 
The Podman v2.0 RESTful API consists of the Libpod API providing support for Podman, and a Docker-compatible API. 
With this new REST API, podman may be called from platforms such as cURL, Postman, Google's Advanced REST 
client, and many others.

=== Docker Compose 

This exercise must be performed as a **rootful** user. In a future version of
RHEL, this restriction will be lifted.

.Become root
--
[source,subs="{markup-in-source}",role=execute]
----
sudo -i
----
--

.Install the `podman-docker` package
--
[source,subs="{markup-in-source}",role=execute]
----
sudo yum install podman-docker -y
----
--

Here is why that is necessary.

Docker compose looks for docker's socket, which is normally `/var/run/docker.sock`
We need to symlink podman's rootful socket there, something like `ln -s /run/podman/podman.sock /var/run/docker.sock`
The podman-docker package also makes a symlink between podman binary and docker. (i.e. `ln -s /usr/bin/podman /usr/bin/docker`)

.As root, start the podman service
--
[source,subs="{markup-in-source}",role=execute]
----
podman --log-level=debug system service -t0
----
--

.In the lower terminal window become a root user
--
[source,subs="{markup-in-source}",role=execute-2]
----
sudo -i
----
--

.Next, create a compose file called `docker-compose.yml`. This container is a simple python web server
--
[source,subs="{markup-in-source}",role=execute-2]
----
cat >> docker-compose.yml << EOF
version: "3.9"
services:
  hello:
    image: "quay.io/bkozdemb/hello"
    ports:
      - "8080:8080"
EOF
----
--

.Setup a Python environment
--
[source,subs="{markup-in-source}",role=execute-2]
----
python -m venv venv
----
--

.Activate the environment
--
[source,subs="{markup-in-source}",role=execute-2]
----
source venv/bin/activate
----
--

.Upgrade `pip` and install `docker-compose`
--
[source,subs="{markup-in-source}",role=execute-2]
----
pip install pip docker-compose -U
----
--

.Run the docker-compose application in the background
--
[source,subs="{markup-in-source}",role=execute-2]
----
docker-compose up -d
----
----
Creating network "lab-user_default" with the default driver
Creating lab-user_hello_1 ... done
----
--

.Confirm the application is running
--
[source,subs="{markup-in-source}",role=execute-2]
----
docker ps
----
----
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                          COMMAND               CREATED        STATUS            PORTS                   NAMES
ae404eeedcc7  quay.io/bkozdemb/hello:latest  /usr/bin/python3 ...  6 seconds ago  Up 6 seconds ago  0.0.0.0:8080->8080/tcp  lab-user_hello_1
----
--

.Visit the application on port 8080
--
[source,subs="{markup-in-source}",role=execute-2]
----
curl http://127.0.0.1:8080
----
----
The Python http server is listening on port 8080
----
--

.Shut down the application
--
[source,subs="{markup-in-source}",role=execute-2]
----
docker-compose down
----
--

=== References

* https://docs.docker.com/compose/gettingstarted/[Docker compose example]
* https://pypi.org/project/docker-compose/[Docker-Compose python]
* https://github.com/containers/podman/tree/main/test/compose[Podman compose tests]
* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#assembly_using-the-container-tools-api_using-the-container-tools-cli[Red Hat container docs]
