:imagesdir: images
:GUID: %guid%
:markup-in-source: verbatim,attributes,quotes
:toc:

In this lab, you will use `podman` in a client/server manner. 
The Podman v2.0 RESTful API consists of the Libpod API providing support for Podman, and a Docker-compatible API. 
With this new REST API, podman may be called from platforms such as cURL, Postman, Google’s Advanced REST 
client, and many others.


==== Podman API demo

This exercise can be performed on the bastion as a **rootless** user.

===== Set up a Python environment

```
sudo yum install python38 -y
```
```
sudo alternatives --set python /usr/bin/python3.8
```
```
python --version
```
Output
```
Python 3.8.6
```
```
python -m venv ~/venv
```
```
source ~/venv/bin/activate
```

The shell prompt should change.
```
(venv) [lab-user@bastion 0 ~]$
```

Install a few dependencies.
```
pip install pip requests -U
```

Add the following Python client code into a file called `podman-client.py`. Copy/paste should work here.

```
cat >> podman-client.py <<EOF
import json
import requests

url = "http://localhost:8080"
req = f'{url}/v1.40.0/libpod/info'
response = requests.get(req)
print(response)

response.raise_for_status()

info = json.loads(response.text)
print(type(info))
print(info['host']['security'])
EOF
```

In the upper terminal, launch the podman API service.
```
podman system service tcp:localhost:8080 --log-level=debug --time=0
```

In the lower termnal, run the `podman-client.py`  that was just created.
```
python podman-client.py
```

Expected output.
```
<Response [200]>
<class 'dict'>
{'apparmorEnabled': False, 'capabilities': 'CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT', 'rootless': True, 'seccompEnabled': True, 'selinuxEnabled': True}
```


==== Docker Compose 

This exercise must be performed as a **rootful** user. In a future version of
RHEL, this restriction will be lifted.

```
sudo -i
```

As root, start the podman service.
```
podman --log-level=debug system service -t0
```

In a separate terminal window as root, create a compose file called `docker-compose.yml`

```
sudo -i
```

```
cat >> docker-compose.yml << EOF
version: "3.9"
services:
  hello:
    image: "quay.io/bkozdemb/hello"
    ports:
      - "8080:8080"
EOF
```

Setup a Python environment.
```
python -m venv venv
```
```
source venv/bin/activate
```

Upgrade `pip` and install `docker-compose`.
```
pip install pip docker-compose -U
```

Run the application in the background.
```
docker-compose up -d
```
Expected output.
```
Creating network "lab-user_default" with the default driver
Creating lab-user_hello_1 ... done
```

Confirm the application is running.
```
docker ps
```
Sample output.
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                          COMMAND               CREATED        STATUS            PORTS                   NAMES
ae404eeedcc7  quay.io/bkozdemb/hello:latest  /usr/bin/python3 ...  6 seconds ago  Up 6 seconds ago  0.0.0.0:8080->8080/tcp  lab-user_hello_1
```

Visit the application on port 8080.
```
curl http://127.0.0.1:8080
```

Expected output.
```
The Python http server is listening on port 8080
```

Shutdown the application.
```
docker-compose down
```

References

[Python example Blog post](https://www.redhat.com/sysadmin/podman-python-bash)
[Clean storage code](https://raw.githubusercontent.com/containers/Demos/main/restful_api/clean_storage.py)
[Docker compose example](https://docs.docker.com/compose/gettingstarted/)
[Docker-Compose python](https://pypi.org/project/docker-compose/)
[Podman compose tests](https://github.com/containers/podman/tree/main/test/compose)
[Red Hat container docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#assembly_using-the-container-tools-api_using-the-container-tools-cli)

